from sqlalchemy import Column, Integer, Float, String, ForeignKey, Date, DateTime, Numeric, FetchedValue
from sqlalchemy.orm import relationship
from datetime import datetime
from app.database import Base

class Ventana(Base):
    __tablename__ = "ventana"
    ventana_id = Column(Integer, primary_key=True, autoincrement=True)
    codigo = Column(String(100), nullable=False, unique=True)
    fecha_mapeo = Column(Date, nullable=True)
    mapeador = Column(String(200), nullable=True)
    campania = Column(Integer, nullable=True)
    este_ini = Column(Numeric(18, 6), nullable=False)
    norte_ini = Column(Numeric(18, 6), nullable=False)
    cota_ini = Column(Numeric(18, 6), nullable=False)
    este_fin = Column(Numeric(18, 6), nullable=False)
    norte_fin = Column(Numeric(18, 6), nullable=False)
    cota_fin = Column(Numeric(18, 6), nullable=False)
    largo_m = Column(Float, FetchedValue(), nullable=True)
    altura_m = Column(Numeric(18, 6), nullable=True)
    dip_talud = Column(Numeric(18, 6), nullable=False)
    dipdir_talud = Column(Numeric(18, 6), nullable=True)
    dip_hw = Column(Numeric(18, 6), nullable=True)
    az_hw = Column(Numeric(18, 6), nullable=True)
    alteracion_codigo = Column(String(10), nullable=True)
    intemperismo_codigo = Column(String(10), nullable=True)
    lito_1 = Column(String(100), nullable=True)
    lito_2 = Column(String(100), nullable=True)
    lito_3 = Column(String(100), nullable=True)
    unidad_litologica = Column(String(100), nullable=True)
    sector = Column(String(100), nullable=True)
    fase = Column(Integer, nullable=True)
    nivel = Column(Float, nullable=True)
    sector_geotecnico = Column(String(100), nullable=True)
    turno = Column(String(50), nullable=True)
    creado_en = Column(DateTime, default=datetime.utcnow, nullable=False)
    modificado_en = Column(DateTime, nullable=True, onupdate=datetime.utcnow)

    discontinuidades = relationship("Discontinuidad", back_populates="ventana", cascade="all, delete-orphan")
    rmr_input = relationship("VentanaRmrInput", back_populates="ventana", uselist=False, cascade="all, delete-orphan")

class Discontinuidad(Base):
    __tablename__ = "discontinuidad"
    discontinuidad_id = Column(Integer, primary_key=True, autoincrement=True)
    ventana_id = Column(Integer, ForeignKey("ventana.ventana_id"), nullable=False)
    familia_id = Column(Integer, nullable=True)
    orden_en_familia = Column(Integer, nullable=True)
    distancia_m = Column(Numeric(18, 6), nullable=True)
    tipo_estructura = Column(String(50), nullable=False)
    dip = Column(Numeric(18, 6), nullable=False)
    dip_dir = Column(Numeric(18, 6), nullable=False)
    abertura_mm = Column(Numeric(18, 6), nullable=True)
    espesor_mm = Column(Numeric(18, 6), nullable=True)
    continuidad_m = Column(Numeric(18, 6), nullable=True)
    espaciamiento_m = Column(Numeric(18, 6), nullable=False)
    n_estructuras = Column(Numeric(18, 6), FetchedValue(), nullable=True)
    n_extremos_visibles = Column(Integer, nullable=True)
    terminacion = Column(Integer, nullable=True)
    relleno_1_codigo = Column(String(50), nullable=True)
    relleno_2_codigo = Column(String(50), nullable=True)
    jrc = Column(Integer, nullable=True)
    rugosidad_codigo = Column(Integer, nullable=True)
    forma_estructura = Column(String(50), nullable=True)
    alteracion_codigo = Column(String(10), nullable=True)
    creado_en = Column(DateTime, default=datetime.utcnow, nullable=False)
    modificado_en = Column(DateTime, nullable=True, onupdate=datetime.utcnow)

    ventana = relationship("Ventana", back_populates="discontinuidades")

class VentanaRmrInput(Base):
    __tablename__ = "ventana_rmr_input"
    ventana_id = Column(Integer, ForeignKey("ventana.ventana_id"), primary_key=True)
    agua_codigo = Column(String(10), nullable=False)
    resistencia_codigo = Column(String(50), nullable=False)
    gsi_estructura = Column(String(50), nullable=True)
    gsi_superficie = Column(String(50), nullable=True)
    gsi_visual = Column(Integer, nullable=True)
    control_estructural = Column(Integer, nullable=True)
    efectos_voladura = Column(Integer, nullable=True)
    ucs_mpa = Column(Numeric(18, 2), nullable=True)
    is50_mpa = Column(Numeric(18, 2), nullable=True)
    comentario = Column(String, nullable=True)
    creado_en = Column(DateTime, default=datetime.utcnow, nullable=False)
    modificado_en = Column(DateTime, nullable=True, onupdate=datetime.utcnow)

    ventana = relationship("Ventana", back_populates="rmr_input")

class VentanasFinal(Base):
    __tablename__ = "ventanas_final"
    id = Column(Integer, primary_key=True, autoincrement=False)
    celda = Column(String(100), nullable=False)
    este_from = Column(Float, nullable=False)
    norte_from = Column(Float, nullable=False)
    cota_from = Column(Float, nullable=False)
    este_to = Column(Float, nullable=False)
    norte_to = Column(Float, nullable=False)
    cota_to = Column(Float, nullable=False)
    dist_celda = Column(Float, nullable=True)
    altura = Column(Float, nullable=True)
    dip = Column(Float, nullable=True)
    az_hole = Column(Float, nullable=True)
    dip_talud = Column(Float, nullable=True)
    dip_dir_talud = Column(Numeric(18, 2), nullable=True)
    intemperismo = Column(String(100), nullable=True)
    cond_agua_76 = Column(String(100), nullable=True)
    cond_agua_valor_76 = Column(Integer, nullable=True)
    dureza_76 = Column(String(100), nullable=True)
    resistencia_est_valor_76 = Column(Integer, nullable=True)
    gsi_visual_76 = Column(Integer, nullable=True)
    control_estructural_76 = Column(Integer, nullable=True)
    efectos_voladura_76 = Column(Integer, nullable=True)
    rqd_valor_76 = Column(Integer, nullable=True)
    rqd_76 = Column(Float, nullable=True)
    freq_fractura_m_76 = Column(Float, nullable=True)
    tam_bloques_m3_76 = Column(Float, nullable=True)
    espaciamiento_prom_76 = Column(Float, nullable=True)
    espaciamiento_valor_76 = Column(Integer, nullable=True)
    cond_discontinuidad_valor_76 = Column(Float, nullable=True)
    rmr_76 = Column(Float, nullable=True)
    ucs_mpa = Column(Float, nullable=True)
    is50_mpa = Column(Float, nullable=True)
    cond_agua_89 = Column(String(100), nullable=True)
    cond_agua_valor_89 = Column(Integer, nullable=True)
    dureza_89 = Column(String(100), nullable=True)
    resistencia_est_valor_89 = Column(Float, nullable=True)
    gsi_visual_89 = Column(Integer, nullable=True)
    control_estructural_89 = Column(Integer, nullable=True)
    efecto_voladura_89 = Column(Integer, nullable=True)
    rqd_valor_89 = Column(Float, nullable=True)
    rqd_89 = Column(Float, nullable=True)
    freq_fractura_m_89 = Column(Float, nullable=True)
    tam_bloques_m3_89 = Column(Float, nullable=True)
    espaciamiento_prom_89 = Column(Float, nullable=True)
    espaciamiento_valor_89 = Column(Float, nullable=True)
    cond_discontinuidad_valor_89 = Column(Float, nullable=True)
    rmr_89 = Column(Float, nullable=True)
    fecha = Column(DateTime, nullable=True)
    comentario = Column(String, nullable=True)
    dist_estructura = Column(Float, nullable=True)
    angulo_estruct_teta = Column(Float, nullable=True)
    angulo_estruct_alfa = Column(Float, nullable=True)
    estruct_x = Column(Float, nullable=True)
    struct_y = Column(Float, nullable=True)
    struct_z = Column(Float, nullable=True)
    tipo_estructura = Column(String(50), nullable=False)
    dip_estructura = Column(Integer, nullable=False)
    dip_dir_estructura = Column(Numeric(18, 6), nullable=False)
    num_estructuras = Column(Integer, nullable=True)
    abertura_mm = Column(Float, nullable=False)
    espesor_mm = Column(Numeric(18, 6), nullable=False)
    continuidad_m = Column(Numeric(18, 6), nullable=False)
    espaciamiento_m = Column(Numeric(18, 6), nullable=True)
    num_extremos_visibles = Column(Integer, nullable=True)
    tipo_relleno_1 = Column(String(100), nullable=False)
    tipo_relleno_2 = Column(String(100), nullable=False)
    jrc = Column(Integer, nullable=True)
    rugosidad_estructuras = Column(Integer, nullable=False)
    forma_estructura = Column(String(100), nullable=False)
    alteracion = Column(String(100), nullable=False)
    geotecnico = Column(String(200), nullable=True)
    nivel = Column(Float, nullable=True)
    lito_1 = Column(String(100), nullable=True)
    lito_2 = Column(String(100), nullable=True)
    lito_3 = Column(String(100), nullable=True)
    unidad_litologica = Column(String(100), nullable=True)
    sector_geotecnico = Column(String(100), nullable=False)
    campania = Column(Integer, nullable=False)
    turno = Column(String(50), nullable=True)

class EnsayoPLTIrregular(Base):
    __tablename__ = "ensayo_plt_irregular"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    campana = Column(Integer, nullable=False)
    fecha_ensayo = Column(Date, nullable=False)
    sector_geotecnico = Column(String(100), nullable=True)
    ejecutado_por = Column(String(200), nullable=False)
    zona_mapeo = Column(String(200), nullable=False)
    nivel = Column(Float, nullable=False)
    celda_mapeo = Column(String(100), nullable=False)
    muestra = Column(String(100), nullable=False)
    codigo_muestra = Column(String(100), nullable=False)
    litologia_1 = Column(String(100), nullable=False)
    litologia_2 = Column(String(100), nullable=True)
    litologia_3 = Column(String(100), nullable=True)
    tipo_litologico = Column(String(200), nullable=False)
    este = Column(Float, nullable=True)
    norte = Column(Float, nullable=True)
    elevacion = Column(Float, nullable=True)
    espesor_d = Column(Float, nullable=True)
    longitud_l = Column(Float, nullable=True)
    ancho_w1 = Column(Float, nullable=True)
    ancho_w2 = Column(Float, nullable=True)
    fuerza_p = Column(Float, nullable=True)
    direccion_rotura = Column(String(50), nullable=True)
    tipo_fractura = Column(String(50), nullable=True)
    factor_conversion_k = Column(Float, nullable=True)
    observaciones = Column(String(1000), nullable=True)
    creado_en = Column(DateTime, default=datetime.utcnow, nullable=False)
    modificado_en = Column(DateTime, nullable=True, onupdate=datetime.utcnow)

